#Numpy-Numerical python

In [ ]:
import numpy as np

In [ ]:
#create an array using numpy
a=np.array([12,49,28,39])
a

array([12, 49, 28, 39])

In [ ]:
#checking dimension of an array
a.ndim

1

In [ ]:
#creating two dimension array with numpy
b=np.array([[1,0,2],[3,5,7]])
b

array([[1, 0, 2],
       [3, 5, 7]])

In [ ]:
b.ndim

2

In [ ]:
# 3D array
c=np.array([[[1,2],[3,6],[9,0]]])
c
c.ndim

3

##Zero's and One's

In [ ]:
# creating array with full zeros and ones
x=np.zeros(5)
print(x)
x.ndim

[0. 0. 0. 0. 0.]


1

In [ ]:
y=np.ones(6)
y

array([1., 1., 1., 1., 1., 1.])

In [ ]:
#create a 3D array with 4 rows and 5 columns & all the elements should be 1
z=np.ones(5)
a=np.array([[[z],[z],[z],[z]]])
a

array([[[[1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.]]]])

In [ ]:
a.ndim

4

In [ ]:
s=np.ones((3,4,5))

In [ ]:
s

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [ ]:
s.ndim

3

##Function used in numpy

In [ ]:
var=np.array([99,10,11,525])
var

array([ 99,  10,  11, 525])

In [ ]:
type(var)

numpy.ndarray

In [ ]:
var.argmax() # max value-index value

3

In [ ]:
var.argmin() #min value-index value

1

In [ ]:
var[3]

525

In [ ]:
var1=np.array([12,23,45,67,89,1,24,46,79])
var1

array([12, 23, 45, 67, 89,  1, 24, 46, 79])

In [ ]:
var1[:5]

array([12, 23, 45, 67, 89])

In [ ]:
var1[2:-2]

array([45, 67, 89,  1, 24])

In [ ]:
var1[-1]

79

In [ ]:
var1.dtype   #it can check the data type

dtype('int64')

In [ ]:
var2=np.array([12.33,23,45,67,89,1,24,46,79])
var2

array([12.33, 23.  , 45.  , 67.  , 89.  ,  1.  , 24.  , 46.  , 79.  ])

In [ ]:
var2.dtype

dtype('float64')

In [ ]:
var1.size #it can check the size

9

In [ ]:
#create an numpy with size 5 and datatype of floating point

p=np.array([1.1,2,3,4,5])
print(p.size)
print(p.dtype)


5
float64


In [ ]:
''' create a 2D array
    4 arrays in the external array
    it should have two elements in each'''

q=np.zeros((4,2))
q

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
q.ndim

2

# Resize and Reshape

In [ ]:
r=np.arange(12)
r


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
r1=r.reshape(4,3)
r1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
r1.max()

11

In [ ]:
r1.min()

0

In [ ]:
np.sqrt(r1)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479]])

In [ ]:
np.log(r1)

<ipython-input-65-518b9941ea25>:1: RuntimeWarning: divide by zero encountered in log
  np.log(r1)


array([[      -inf, 0.        , 0.69314718],
       [1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154],
       [2.19722458, 2.30258509, 2.39789527]])

In [ ]:
np.exp(r1)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [ ]:
r1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
r1.shape  # it tells rows and columns

(4, 3)

#Floor and Ceil

In [ ]:
a=np.array([2.3,4.6,7.5,8.9])
a

array([2.3, 4.6, 7.5, 8.9])

In [ ]:
np.floor(a)

array([2., 4., 7., 8.])

In [ ]:
np.round(a)

array([2., 5., 8., 9.])

In [ ]:
np.ceil(a)

array([3., 5., 8., 9.])

# Stacking


In [ ]:
a1=np.arange(10).reshape(2,5)
a2=np.arange(20).reshape(4,5)

In [ ]:
a1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
a2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
np.vstack((a1,a2))  #vertical stacking - no. of columns should be equal in both arrays

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
a3=np.arange(12).reshape(4,3)
a4=np.arange(24).reshape(4,6)


In [ ]:
a3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
a4

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
np.hstack((a3,a4)) # horizontal stacking-no. of rows should be equal in both arrays

array([[ 0,  1,  2,  0,  1,  2,  3,  4,  5],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 6,  7,  8, 12, 13, 14, 15, 16, 17],
       [ 9, 10, 11, 18, 19, 20, 21, 22, 23]])

#Numpy Split

In [ ]:
arr=np.arange(100).reshape(10,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
np.vsplit(arr,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]),
 array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])]

In [ ]:
np.hsplit(arr,2)

[array([[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14],
        [20, 21, 22, 23, 24],
        [30, 31, 32, 33, 34],
        [40, 41, 42, 43, 44],
        [50, 51, 52, 53, 54],
        [60, 61, 62, 63, 64],
        [70, 71, 72, 73, 74],
        [80, 81, 82, 83, 84],
        [90, 91, 92, 93, 94]]),
 array([[ 5,  6,  7,  8,  9],
        [15, 16, 17, 18, 19],
        [25, 26, 27, 28, 29],
        [35, 36, 37, 38, 39],
        [45, 46, 47, 48, 49],
        [55, 56, 57, 58, 59],
        [65, 66, 67, 68, 69],
        [75, 76, 77, 78, 79],
        [85, 86, 87, 88, 89],
        [95, 96, 97, 98, 99]])]

In [ ]:
np.hsplit(arr,5)

[array([[ 0,  1],
        [10, 11],
        [20, 21],
        [30, 31],
        [40, 41],
        [50, 51],
        [60, 61],
        [70, 71],
        [80, 81],
        [90, 91]]),
 array([[ 2,  3],
        [12, 13],
        [22, 23],
        [32, 33],
        [42, 43],
        [52, 53],
        [62, 63],
        [72, 73],
        [82, 83],
        [92, 93]]),
 array([[ 4,  5],
        [14, 15],
        [24, 25],
        [34, 35],
        [44, 45],
        [54, 55],
        [64, 65],
        [74, 75],
        [84, 85],
        [94, 95]]),
 array([[ 6,  7],
        [16, 17],
        [26, 27],
        [36, 37],
        [46, 47],
        [56, 57],
        [66, 67],
        [76, 77],
        [86, 87],
        [96, 97]]),
 array([[ 8,  9],
        [18, 19],
        [28, 29],
        [38, 39],
        [48, 49],
        [58, 59],
        [68, 69],
        [78, 79],
        [88, 89],
        [98, 99]])]

In [ ]:
# create a numpy array with shape of 200, array should be 20 rows and 10 columns
# split the array into vertically and horizondally


In [ ]:
s=np.arange(200).reshape(20,10)

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169

In [92]:
np.vsplit(s,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]),
 array([[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
        [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
        [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
        [160, 161, 162, 163, 164, 165, 166, 167, 168, 169],
        [170, 171, 172, 173, 174, 175, 176, 177, 178, 179],
        [180, 181,

In [93]:
np.hsplit(s,2)

[array([[  0,   1,   2,   3,   4],
        [ 10,  11,  12,  13,  14],
        [ 20,  21,  22,  23,  24],
        [ 30,  31,  32,  33,  34],
        [ 40,  41,  42,  43,  44],
        [ 50,  51,  52,  53,  54],
        [ 60,  61,  62,  63,  64],
        [ 70,  71,  72,  73,  74],
        [ 80,  81,  82,  83,  84],
        [ 90,  91,  92,  93,  94],
        [100, 101, 102, 103, 104],
        [110, 111, 112, 113, 114],
        [120, 121, 122, 123, 124],
        [130, 131, 132, 133, 134],
        [140, 141, 142, 143, 144],
        [150, 151, 152, 153, 154],
        [160, 161, 162, 163, 164],
        [170, 171, 172, 173, 174],
        [180, 181, 182, 183, 184],
        [190, 191, 192, 193, 194]]),
 array([[  5,   6,   7,   8,   9],
        [ 15,  16,  17,  18,  19],
        [ 25,  26,  27,  28,  29],
        [ 35,  36,  37,  38,  39],
        [ 45,  46,  47,  48,  49],
        [ 55,  56,  57,  58,  59],
        [ 65,  66,  67,  68,  69],
        [ 75,  76,  77,  78,  79],
        [ 85,  86,